
from collections import deque
import re
from typing import List, OrderedDict

import sys
sys.path.append( '.' )
from src.chp1_replication.pattern_finding_algorithm import PatternFindingAlgorithm

class SequencingAlgorithm:

    def __init__(self) -> None:
        self.codon = {"UUU":"F", "UUC":"F", "UUA":"L", "UUG":"L",
                      "UCU":"S", "UCC":"S", "UCA":"S", "UCG":"S",
                      "UAU":"Y", "UAC":"Y", "UAA":"STOP", "UAG":"STOP",
                      "UGU":"C", "UGC":"C", "UGA":"STOP", "UGG":"W",
                      "CUU":"L", "CUC":"L", "CUA":"L", "CUG":"L",
                      "CCU":"P", "CCC":"P", "CCA":"P", "CCG":"P",
                      "CAU":"H", "CAC":"H", "CAA":"Q", "CAG":"Q",
                      "CGU":"R", "CGC":"R", "CGA":"R", "CGG":"R",
                      "AUU":"I", "AUC":"I", "AUA":"I", "AUG":"M",
                      "ACU":"T", "ACC":"T", "ACA":"T", "ACG":"T",
                      "AAU":"N", "AAC":"N", "AAA":"K", "AAG":"K",
                      "AGU":"S", "AGC":"S", "AGA":"R", "AGG":"R",
                      "GUU":"V", "GUC":"V", "GUA":"V", "GUG":"V",
                      "GCU":"A", "GCC":"A", "GCA":"A", "GCG":"A",
                      "GAU":"D", "GAC":"D", "GAA":"E", "GAG":"E",
                      "GGU":"G", "GGC":"G", "GGA":"G", "GGG":"G"}
        self.patternAlgo = PatternFindingAlgorithm()

    def rna_to_amino(self, rna:str) -> str:

        transcribed = []
        for i in range(0, len(rna), 3):
            code = self.codon[rna[i:i+3]]

            if code == "STOP":
                break
            transcribed.append(code)

        return ''.join(transcribed)


    def peptide_encodings(self, dna:str, peptide:str) -> List[str]:

        encode_patterns = []

        window = len(peptide) * 3

        for i in range(len(dna)-window):
            transcribed1 = self.rna_to_amino(re.sub('T', 'U', dna[i:i+window]))
            transcribed2 = self.rna_to_amino(re.sub('T', 'U', self.patternAlgo.reverse_complement(dna[i:i+window])))
            if transcribed1 == peptide or transcribed2 == peptide:
                encode_patterns.append(dna[i:i+window])

        return encode_patterns


uut = SequencingAlgorithm()


res = uut.peptide_encodings("GGGCGCGTCCAGTATACTGGTAACGCCACAATTATGGGGCACAAATAAGTTAGATCGTATCTACGAGAACGGAAACTATCGGTACAAGACAGCTACTAAACCGGGTCAACCACGAGTGAAGCGCATACTGGTCAATTTCTATACCCGTATGAGCCTTCGTCGTACATGGTTCCTATGCATCACCGTGAAGCAGCAGGAGGAATAGGCTTCCAGAACCGCCTGCCCAATTGCTTCAGCACGTAACGCGAAACCAAAGAATAGCGGTAATTGCCGTTCTCATAGGCTAAGCGCGAAGTTCGATTGTTATAGGCGATTGGCCTTCCAGTACAACTGAGCTTTGTCAGCTTTGAGAGCTGGGCCCCACTAAGACAACCTGGCAACGGAACTTTTACATCTGAAAACCGTATGGACGCTCCTATCCATTGGGCATCGCCCGAGGGTGCCTGCGCGTGGGGTCGTCCAAGAGATTAAATGGGCATCCGATGGCTTCTAGCTGAGGGCGGATAGGCCCTATCTGCCTGCAGGTCAAGGGATGATATCTCTGGTCGCCTGTCGCCGGAGGTTTGCACCGACTAGCTCGTGAGTGATTGTGTGTTATCAACTAAGGGTGGAATAATTTTCCACATTCGTGGCCTAATTGCATTAGTAAACCACACCATTGATCGTCCTACGTAACCAGCTCCGGAGATGGAACGTATTATCACGTTTCTACGTTAAATCGCTGCGAGCCTTTCGGTTTGGGCCCTACCTCCTAGCGAAATATGAGGTATGGCTATGAGGTCGAAACCGACCAAGCGCTTTAATTGCAAGTTTACCACATTCTCCACGAGGCTTAAGTTTGATTATGAGGTTCGGACGAACTTGATTATAATGTTAAGGCCAACCTCTTGGAGCCCGCCCTGATCACCTACTCTACGAGAATGGGAATTACCGCTACTTCTCGACACGCAATCGTATGTTGCAACTACATTATTCATCTGGTCAAGGAACAACGCCACTGGGGAAATAGCACTGGGGGAACCTTGGTACGACACGTCTTCGTGTTATTAAGCTATGCTCAAATTCGCTCATTGAACAACCTCAACTGAGGTGCCAAGAGACCCCTTAGAACTGGCACGACCCCTGCGAGCCATACGGGAACTCGGGTGCCGGCATAGGGTACATTGTGACCCAGCATAGATTGTACTGATACCTATAATTGCCGTTTTCATAAAATAAGGGAGCATGGCTGGGTGCACCAGTGTAAGTAGGCTGTGCCTTAGTCATAGATTAAGTGCTACACGTTATTGCTGTCCTAATTTTGATCCAGTGAGCCCAAGAAAAGCCGGCGCTTCAGAGGACTAATAATTTATTAATTAAGCCGACCAAGGGGATCTTGTGGCGAGGTATGAACTGACGATAGTCGACCCGCCACCGTGCAGGTCGAGCTGATCTGGCGCGAGTGATGCCATGGCTTGAAAACTAGGGGCTCGCGATATTAAGAATTACCGGACTGATTGGCAGAGCACGTTAAAGGGCTATGAGAATGGCAATTACAGATATCGGACACTAACGTCTCCCAGCAATAGTCGATCCGGTATCTGTAATTTCCGTTCTCATAAATGATATTGCAATCTCTGGTGTCAACGGAACCCTATACTACCTGTCATACCTCAACTCCTCTCGTTAACGGGTTGGTCATAGGGCGTCCGGACTATGGCTAGATGGGTGAGGGTCTTACACGGCGACCCCAAAAGGGTTTGCAGCACGGAATGCGAAGTCTACGCGGAGAGACCAACCTCACCGTGGCCCATATACCATCCGGTACTTCGCATGTTGGATATTCGATCAGTAGAGGTTAATGGACGAATACTGCTTTCGCCTCAGATGGGCGCTACGGGATGCACGCTGTTCAGCCTATGACGCCCTTTTAGCGGGAATTCTTTAGTAGTCCAGACGTCTTACTCTCAGCGCATACATCGCAGGATCGCTTGTGGGGATATTTACCCTCAGGCGCCGAGGGGCATTACCTATCTTGCAGCGCGAGTACTTGCCAGCCAATTGGAGCTCAGGGATGGTGGTGGGTTTCTACCCCTGACAATAACGGTAATTACCGTTTTCGTATTTAGACGCTAAGACCATCACGATTTCACCGAAACAGTAGTGGATAACCACTAGAATTCCTTCGCTATGACTGTAGGGGGCCGGGATGAATAGATGATGGAGACGTGCCTGCGGGAGTTGATGTGATGAGAAGCCCTCAACTCTCACGGATTCACGTTACGTTATTCACGAGCAGATTTGGGAGAATGAGTCAGGTTATTTCGTGGGCTTAAGGGGAGCTGCGCTTAGGTCCCTTCATGCTTCGCGGGTTCAAGCTTCAATAGATAGAGGAGGTTATGGACGCGGATGTGGAACGCTCCCAGTAGCTTCTGGGGAAATAGGTGAACACGTCACTCGCCCAGCTGCCAGACATTAGTAAGCCTGTCCAAATGTACGGGTTTACTCATTCAGACCTCGAGCAGTGTTATCTACGTCATCTCGTCCTGAGACTCTAGATATAAGCTTAACGAAGTGAGTGCCGCCCCTGCGCCAGTGGTTGGACTGGCGTGTGGTGTACCGAAGCCAGCCCGTATAACATCCGAAGGCTCACTTCTGAAAAGATCTTTTGTAGTCCTGAGATAAGGACGTACGGGCTAAGGTGTGTGAACAAATGGTCTGATGTAGCTAGGAGAAAAACCCCACCTATGAACCAGGGCTATCCCGTAACTCATAGCGTGACCTGGATAGGAGGCCTAAGGTCATTAACAGGCCACACGGGGACGCGAAGGGCATAGATCTCCGCACATGTGCACGGCTAGTGTACATAAGTAGGCGCTTATGCCGTTGCTAGGTCCAATATATTGCGCCGACTACCGTGGCGCGACAACTACCGAACAATACTTGCTACGAACTACGTGTATCGTTCCAGAGTACGCTGTGTTGATGGTCGGCTTATTGTCACTCTTCGACATGGGAGCCGCCTCTATAGTTAACGATCGGAGCCCCAGCCGGAGCTGAAGTCCGAAAGTCTAACTTTTACTGAACATATATGCAAGGGACTGACTGGACCTAGCACCATAGTGTTACAGGTTAAAATACTAACCGTCATAACGATAATTGCCGTTCTCATAGGACAAATCAAAATGACGACACCGTGGTTAATATTCCGCTTACCATTGTCTATACGTGGATCCTGAACTCTTTGTAGCCGGTTCAACCATTCATCATAGGAAAGTGATCGGGACTCTCGTGAGGCCTGCATGGTACTGCTATGCTGCCTTTCATCCGACGTACTATCCCGAACACGCGAATATTTCTAGTAATCTCGTAATTCAGACCAAAAACGTGCGTTTCGCCGACGTTGCTGGGGGGCCAATCCGATCGTATTTCTCCTTAGGGTTAACAGATCTACGCGTTTATGACTGGCGTGCTGTAGCGATTCCCTTGGACATAACGAGGCATCGCTACATTAAGAATTACGGGTTGTAAAGATTTTTCTCAGCTCACCATCGCAGGTACCCCCTGGTCACGCTTAATGAAGCCCGACATAACGATAGTTACCATTCTCGTATCGCCGCCCCTAGCAACAATTTCGTCGCAAATGTCGAGGACTACCGACTGTTGGCACTGACCCGCCTTCGTCCGATCCAGGCAATGGGACGGCTGCTTCAGACTTCCTGCCCGACAGCTGGGATGTGAACAAACTGCTACAAGGGTCACCTATCGGCAACAGCAATGACGAAAGGAATGGCAGAACATTCGTCGCCCGGGTGGATTAGCCAAGGTTACTGTACTCTTAGGATAATCCATGAGCCAAACATAAGGAAACACTTACGTCTTCGACTGCATCGTATGCCGAGTAGGTTGGCATCTTCTCGACACGAGGACCAAAATCCCGCAACTGTGCCGCGACGCTCCACCTTGTCAGTCTCGAGTGTATAGTAGCGGGTATCGGAGACGCTCTGGGCGGGCGAGATTCACAAAAGCAGCGCGTAAAAAGTGACAAGATGGGCTGAAATCGGACCAAAACTCATGTGATTATAATCTCATAAATGTATAGCGACCGCACTGACAAATGACCTAGGGGCTGATGTGTGAGATACAATCCTTCGTTGCCTTGCAGTAGCAATCGCCCCCCTATACGTCGCTTGCGAATAGCGCATGCTCACATCCATTTTTGACGGTTCCCCTAGACATTAGCATGCGTCTAGCCCTGTTCAAAGTCAACGACCAAACGACCAGTCCCACAATAACGATATGAGCATTATTACCAAAACGCAAACTCAGCGCCAATTAAAAGTAGGTCCTGACGGCCGATGGCCTTCTCTGTATACCAATCGAACTGGTCCGGCACTAGCAGACTAGCACTTCAAGGCGACCAGTCGACTTATGAGAACGGTAACTATCGGTATACAGTGATCGCAGCAGCACTTGACTGCTGCGTCTGGGCGGGCAAGACCTGTTCTAGCAATTCACCCCTGACGGTTAAGTAAAGCCAGGATTGGCAACCCTTCGTCCTGCGGTCATTCTGTCGAACCTTTCTGGGGATGGCTCAGGGAATGGACAAATTTTTTGTAAGTGTCTCCCAACCGGTAACGTTCAACCTCATTATTGGCGAAACCCATGAAGTGTCTAGGTGCGTATGCATATAATTGTAGGTGCGGTCAGAAAGATCGATAGGTTTGGTGTAGCGCTATAACTATCCGGCGAAAGACTATACACAGGCCATTAATAACACTGCAAAGGGCGGGAACGCTGTCGTTAGCGTTTCATAGCTCGGATCGTGTCCTACTGTGACTTGTCATCTTTAACAAGCCGTTAGAGGGGTCGCCGGTGAAACCCGCAGTAATGTTAAAACCTGGAGTGCCATCGCTCTATCAGCTTTCTTCGGGATATGCACCTCCCTTGCATCGGAGAGTCAGCGCGCGTCTAAATAGCGGTAATTACCATTCTCATACTTGTGGACAATGTGAATGTCTGGATATGGCACGTAGACAGTCGGATCCAACAGAGAAAGCATCATGATCCCCGGGAGCTCTCCTGGTCCTTGCTCAACGAAAGCTAGTTGATTACCCCAGTCTAACATAACTAAGTGAAACGCCTGCTTCGGACTTACCTGCTATACCTACTGCCACGCCAGAACAGAAATCCACCGCAGAGGGAGTGTATGGGCATGCAACTATATTTGTATGTATGTGCAACAACCTCTTCTGACAGTGTGATTTACTCTGTATCGATAATTGCCATTCTCATATTGACAAACTACAGATCCATGTATACTTTGCGCTTGCAAGAGAGTACCGCAGATAAGTGCTTAGCTTTTATGGAAGGCACAAGGTTAATCTATTTTCAACACGACCCTCCCATTTACATCCATTACTCACCATAGAGGACGCAAACGTAATACTACAGAACTGTTGGAAAGAGCCGTTATTATCAAAAACATACCGGTAGTTGCCATTTTCATACTTCAAGTAATCATTAAAATGGTTCCCAGTTGTCTATTGGGGTATCCAGTTGAATAACAACGTAGAGGTGTAGACGCGTTTACCTAGTTCTTACCTGCATTGTCGCGTATATGGAATAATGTCCAAAAGGGAGACGGTTGCGCAATTCAAATCTATCCTCGAATACCTAGCGGTCGCAGCTGTGGCATATTAGTATTCACTTTGTGTTGGCGCGCGGGTCATTGAGGTGCAGAGCGATTCCATGTGGGCGGGTACGGTGCGCACGATTTCCATCTGAATATAGACGAGAAGATATCGCTTCGCCAAAGATGAACCAAACCATCTCCGTATCAGCTGCGGCATCACTTACGTAGTTGAAATAACGGCGAAGCTGTATCAGTGTTGGTGTTCCATTGGTTGCTATCTGTAGTCCACCCCCGTCAACCATTTTAATAAAAGCTAAAATGTGCCGCTTCGCCCTTAGGGTGTCTTACTAACCGGCGACGTAGACATAATCATCACCGAAGCCCGCACAACTACTAAGGAAGAGACCGGAAATACTGTTAGCATGACAAAGCGATTGAATGGCGCTGATATCTTCACCCGAGCGACATCTGCACCTACAGCAATCAACTAGTTCCGGACTGTGGGGCACGAATTATATCCGACGGTAGGCCCGACGCTCAAGGAAGTCGGCGGAACGGCGGCACAAGCAGAAGTAGGGTGTTCCTCATTATAAAAGCATCAGACGATACCAACGCAACCACAAGATTACAATTACAGTTAACCACCTACGGTACATAGGGGACGCTAAGGGCTGCGATTACATAACGATTAAGCGGTGGGTGTTGGTGTTTTTGGATCGGTATGAGAATGGTAATTACCGATACACCCCACTCGCTTTCCGATTCACTTCAATGATACCCACTTCCATACGAGTGGATCCGAGATAGCGGCACTACCGGGGGACAACGCACAGGGCCGTGCTCCGACCGGAGGAGCGTGAGCGACCAGATACTCGAGAAAACTAATTTAATATTGAGGGCCAGTGTGGCTGTGAAGCCCTAAAAACTTCCAAGATGTACCCGTGGATGATATAGAGTATCTGTACGTCGATTACCACTGATCTTTCGCTGCCGTCAACGTTGGACATCTCCCCAACACGGTAATTGTCCGATCATGGTTCAGCCTGCTCTTTCATGACTTTGAGATTCGACGCCTTGGAGTTGTTTTGGCCCCAGCCACTGGGACGTCCAATCACTGCGCTCTGAAAGTTGAGAATCCTAGTACTGACGCTTCTGTACCTGTAATTCCCATTTTCGTAACAGCAAGAAAAGAGTTTTACACCAATTTCGACCGCTTGTCGTTGTTGGAGCTCATGATAGCCATAGTACGAAAACGGTAACTACCGTTACGGGAAAGAACCTGACCTTACGGAGGGTACGCACACTGACTCCGATCAATCCTTAGCAATTTGCTTCGGCCGGTGTCGAACGGCTTGCCAACGGAATCTGTCTCCGCAGTTGCTTACGAGAACGGTAATTATCGGTATACAGTTTTATTTCCTGAAACAGGTTGCTGCTTGACGCAACTCAGCCCTGCGGAATGAAGTAGAGGCTGTACATGATCGAAATATCCTCTTGGTTCATTGGGGTGGGGTTTAGCTTCCTCATCGCCCGTAAATCATACCCGATTACGGTGTATTGCTCAAAGAGCATTAGACAGAGTAGAGGTAGCGATAATTACCATTCTCGTAGGGGGTTGGAGTTTGCCCGTCTGGCAAGACAACCGACACATCCTTGATAGTGTTACTGAAGAAACGTCTATGAACCTGCAGTTGTGGCCTCATAGAGAATAAGTCATGCAATGCAATCACTAAGTCTTTATCCCTTGCTGCGTCACTGAAATTGAACCCACGTAGGAGACCTATCTAAGATTAAGTGCAGCGCAGAGTGGGTACGATTCTGTTGTCACGACGAACCAGTTCTTGGGTGTATTCCTAAGGCAGTAGGGGCGCTTCATTCTTGCCCAACTGTTCGTGCTTAGTCATAGGATGTCGTCCGATAACAATGCCTGATTTGCGTCCATCCCCCAGCCTTTAATCGGACGGTGCCCGAGATGAGTAACGGCATTTACTGGTAGCTGCAGAACCAAACGCACTTAATTGTAGAGAATGAAGAATCTCAAGCCGAGCGGAGAATGCTCGACGCCCAGAAGGACCTCACCTGTCGATGCAAGTCAAGAATTGCCCCCATTATATGAACGGAGTGACCAAAATTTTCAATCTTCCTCATCACACATATTGACATTCGCGTCCCAATACATCTTGATTTAGGTTCAGTGGCTGTAACCACCGTCCCAACCAATGGACAGCCAGTCACTTCGAAGGAACTACAAACCGAGGTTAAAAGAGTCGGGAGCGCGGTGTCGCGGACCTAACCACGTAACTTAGTTGACTTGGGAGCGAGGTTAATAACGATAATTGCCGTTTTCGTAAGATCTAATCGGTAACGTATCGATATGAACAAACAAACCTATTACCCGCCCACTTGTTCATGCTAATCTGGTGGCTTGTTGGGCATGCATAATGGTGAGGCCGCTAGTGCGGCCTACCGAGCAATGTTCTGCCAAAGAGATTGTAACCCCCAAAATCTCTACGGGCTGCGCTCGAATACTGTTCAAGAATTCCGATTTTTATCGGATGTACTAAGTCCCAAAATTTGTTAATTCGCGGACCTCAAGTCGACTGGCGTTTTCTAGGACCGTCTCTCATTGTGAGGCGATGCTGTACAGGAATAGCATGTAGGGAATGAGTGGGAGAGGGCTCGAGTGCGCTCCCTATGACTGCCGTGAGTCCCTCAACAAACTAAGCGGGGCAAATTACGGCCATCCACAGGAGGTCCGCTAGGCTACGAGAATGGCAATTACAGATATAGACGGCTATGCTCCCCCCAAAGCTTGTTCTCGCGAGTGTTATGGAGGTCCCGAGCATACTCGATTAGGGATGGGCCCTTCTGGAATGAAGAATTGCGACCTAAAATCTCGGTGAAGTGATGTCCGAGGAACTGTCCTCTGTACTACAGTGTAGCCACCTTTGTTGGTGGACCTCAACATTGTGAACTCGAGAATGAGGCAAGGCTTACACCAGATCCTTGTGGTATGACTATGTCGCTGCTCAAGGTAATGCACTTCAAGGGATGTCCAAGATCTACATTTTCTGACTCACTTATCTTGCGAGGTGCGGAAGAGTGATAGAGAACCAGCACGACATATACCTAGGTGGGTGCCCCATTCCAGGGAAATAATCCATATGGTATTAAGTAAGGCTCGCAAACACATACCTGTCCCCGTAAGCTGGGAT", "YENGNYRY")

for soln in res:
    print(soln)